# ERRORS
ERROR_RESPONSE = "Has occurred an error"
BODY_REQUIRED = "The body must be a JSON" 
INTERNAL_SERVER_ERROR = "Internal server error"
METHOD_NOT_ALLOWED = "Method not allowed"
UNAUTHORIZED_ERROR = "You are not authorized to access this resource"
VALIDATION_ERROR = "Validation error"
NO_IMAGE_PROVIDED = "No image provided"
INVALID_IMAGE_FORMAT = "Invalid image format, must be jpeg, png or gif"
# VALIDATIONS
IS_REQUIRED = "The field is required"
IS_NUMBER = "The field must be a number"
POSITIVE_NUMBER = "The field must be a positive number"
IS_STRING = "The field must be a string"
IS_DATE = "The field must be a date, format: YYYY-MM-DD"
IS_EMAIL = "The field must be an email"
IS_BOOLEAN = "The field must be a boolean value"
TOKEN_REQUIRED = "User token is required"